### PR TITLE
fix: subgraph create should deduplicated bindings on name conflict

### LINKED ISSUE #2123: Editor V2: Fix pack/unpack subgraph logic regressions
## Summary

Fix regressions in the pack/unpack subgraph logic in editor V2. Use the V1 implementation (#1629) as the reference behavior.

## Rationale

From the Apr 21 CSOM sync: pack/unpack in V2 has issues that were resolved in V1. V1 had edge cases that took non-trivial work to get right, and the V2 port (AI-assisted) appears to have missed some of those cases.

## Acceptance

- [x] Packing a selection into a subgraph in V2 produces equivalent output to V1.
- [ ] Unpacking a subgraph onto the canvas in V2 matches V1 behavior, including the empty-canvas prompt flow from #1629.
- [ ] Edge cases identified during V1 development are explicitly regression-tested.

## Notes

Reference implementation: #1629 (Unpack Subgraphs onto an Empty Canvas, completed in V1). Talk to @camielvs for context on the original edge cases.

---

_Context: Captured from the Tangle / CSOM UX sync on Apr 21, 2026 ([notes](https://docs.google.com/document/d/1GnAq9xcOkcnqwwJDXATM9l2jHzd_xHQDqMkAtUq-jf0/edit?usp=sharing)). Attendees: Matt Beaulne, Camiel van Schoonhoven, Maksym Yezhov._

_Requested by Matt Beaulne <matt.beaulne@shopify.com>._

### PR DESCRIPTION
**Pull request by maxy-shpfy**
## Description

Closes https://github.com/TangleML/tangle-ui/issues/2123

Fixes two bugs in the `createSubgraph` action and adds comprehensive roundtrip tests to verify correctness of `createSubgraph` followed by `unpackSubgraph`.

**Bug 1 – Duplicate port names when grouping external bindings:** When multiple external bindings targeted different selected tasks but shared the same port name (e.g., two tasks both receiving a `trainer_name` input), the subgraph would generate duplicate input/output port names. A `deduplicatePortName` helper is introduced to append a numeric suffix (`_2`, `_3`, …) when a name collision is detected, preventing ghost or duplicate bindings after an unpack.

**Bug 2 –** **`executionOptions`** **not preserved through subgraph creation:** Task `executionOptions` (caching strategy, retry strategy, etc.) were not included in the task snapshot taken during `createSubgraph`, causing them to be silently dropped. The snapshot and task reconstruction now carry `executionOptions` through correctly.

## Type of Change

- [x] Bug fix
- [x] New feature

## Checklist

- [ ] I have tested this does not break current pipelines / runs functionality
- [ ] I have tested the changes on staging

## Test Instructions

The new test suite in `unpackSubgraph.test.ts` covers the following scenarios and can be run directly:

1. Single task roundtrip preserves task count and `componentRef`.
2. Two connected tasks roundtrip preserves binding connectivity.
3. External incoming and outgoing bindings are preserved after roundtrip.
4. Complex graphs with inputs, outputs, and branching produce no ghost or extra bindings.
5. `executionOptions` with `maxCacheStaleness`, `retryStrategy`, or both are preserved.
6. `isEnabled` predicates are preserved.
7. Static `arguments` are preserved.
8. No ghost bindings remain after unpack (all binding endpoints reference real entities).
9. No duplicate bindings when different external sources feed same-named ports on different selected tasks.

## Additional Comments

The `deduplicatePortName` helper is intentionally simple: it tries the base name first, then appends `_2`, `_3`, etc. This matches the convention used elsewhere in the codebase for name collision resolution.

### CODE REVIEW

**Comment by maxy-shpfy** [comment]
* **#2173** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2173?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2172** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2172?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2170** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2170?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2160** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2145** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2145?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2144** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2144?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2143** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2143?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2141** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2141?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2113** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2112** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2111** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2110** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2110?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2110?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2109** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2109?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2108** <a href="https://app.graphite.com/github/pr/TangleML/tangle-ui/2108?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Mbeaulne — APPROVED** [review]

File: src/models/componentSpec/actions/createSubgraph.ts [hunk 1]
```diff
@@ -275,3 +286,15 @@ function groupBy<T>(
...
+  if (!usedNames.has(baseName)) {
+    usedNames.add(baseName);
+    return baseName;
+  }
+  let counter = 2;
+  while (usedNames.has(`${baseName}_${counter}`)) counter++;
+  const unique = `${baseName}_${counter}`;
+  usedNames.add(unique);
+  return unique;
+}
```
Comment (camielvs) [inline src/models/componentSpec/actions/createSubgraph.ts:300]: could this run into conflicts if the a port(s) already have names in the form `name_number`?

**Review by camielvs — APPROVED** [review]
Issue appears to be fixed.

File: src/models/componentSpec/actions/createSubgraph.ts (hunk 1 above)
Comment (camielvs) [reply src/models/componentSpec/actions/createSubgraph.ts:300]: I think the `while` loop may catch this. but worth keeping an eye out once in the wild

**Comment by maxy-shpfy** [comment]
### Merge activity

* **Apr 29, 8:02 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/TangleML/tangle-ui/2110).
* **Apr 29, 8:12 PM UTC**: [Graphite](https://app.graphite.com/github/pr/TangleML/tangle-ui/2110) rebased this pull request as part of a merge.
* **Apr 29, 8:14 PM UTC**: @maxy-shpfy merged this pull request with [Graphite](https://app.graphite.com/github/pr/TangleML/tangle-ui/2110).
